### PR TITLE
udisks: fix not create media dir

### PR DESCRIPTION
**Pull request by Wolftronics-SBC**

### CODE REVIEW

**Comment by Wolftronics-SBC** [comment]
not work automount usb drive "not automountd package"... at least I do not work if I created the media directory working.

**Comment by tomlohave** [comment]
Le 31/10/2017 à 19:06, Wolftronics-SBC a écrit :
> not work automount usb drive "not automountd package"... at least I do 
> not work if I created the media directory working.
Sorry, I do not understand very well.
udisks mount the usb disks (ntfs fat, ext{2,3,4}) with no problem under 
/media using this systemd file
Can you post something ?
ie if you add an usb disk, what returns dmesg and what is the content of
/proc/mounts ? (off course with udisks active via systemd)

Cheers !

**Comment by Wolftronics-SBC** [comment]
I look at dmesg /proc/mounts but I can only answer tomorrow.

**Comment by tomlohave** [comment]
Le 31/10/2017 à 19:29, Wolftronics-SBC a écrit :
> I look at dmesg /proc/mounts but I can only answer tomorrow.
no problem, no hurry
I will comit the 2nd patch (about zlib)


B.R

**Comment by Wolftronics-SBC** [comment]
[https://pastebin.com/UDPTCyy4](url) dmesg_no_media_dir_usbconnected.log
[https://pastebin.com/4BydWAGR](url) dmesg_with_media_dir_usbconnected.log
[https://pastebin.com/3ePtAkfF](url) proc_mounts_no_media_dir_usbconnected.log
[https://pastebin.com/Wmqvmskx](url)  proc_mounts_with_media_dir_usbconnected.log

**Comment by tomlohave** [comment]
ok, and who mount the drive ?
If you remove this systemd file you have no helper to mount usb drive
What returns 'systemctl status udisks -l' ?

**Comment by tomlohave** [comment]
ok, I see, the systemd file installed is not the good one. It can explain your problem not having /media created at boot time.

**Comment by Wolftronics-SBC** [comment]
yes :)

**Pull request merged**
